name = "my-slides"
defaultTargets = ["Slides", "generate-slides"]

[[require]]
name = "verso-slides"
git = "https://github.com/leanprover/verso-slides.git"
rev = "main"

[[lean_lib]]
name = "Diagrams"

[[lean_lib]]
name = "Slides"

[[lean_exe]]
name = "generate-slides"
root = "Main"
